# -*- coding: utf-8 -*-
"""DataAnalyst4thProject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13XwpLKZqKExWX23t-gd_RWJy7yr2QwL1
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""Using this dataset, we answered multiple questions with Python in our Project.

Q. 1) For 'House of Cards', what is the Show Id and Who is the Director of this show ?

Q. 2) In which year the highest number of the TV Shows & Movies were released ? Show with Bar Graph.

Q. 3) How many Movies & TV Shows are in the dataset ? Show with Bar Graph.

Q. 4) Show all the Movies that were released in year 2000.

Q. 5) Show only the Titles of all TV Shows that were released in India only.

Q. 6) Show Top 10 Directors, who gave the highest number of TV Shows & Movies to Netflix ?

Q. 7) Show all the Records, where "Category is Movie and Type is Comedies" or "Country is United Kingdom".

Q. 8) In how many movies/shows, Tom Cruise was cast ?

Q. 9) What are the different Ratings defined by Netflix ?
Q. 9.1) How many Movies got the 'TV-14' rating, in Canada ?
Q. 9.2) How many TV Shows got the 'R' rating, after year 2018 ?

Q. 10) What is the maximum duration of a Movie/Show on Netflix ?

Q. 11) Which individual country has the Highest No. of TV Shows ?

Q. 12) How can we sort the dataset by Year ?

Q. 13) Find all the instances where: Category is 'Movie' and Type is 'Dramas' or Category is 'TV Show' & Type is 'Kids' TV'.
"""

df = pd.read_csv('/content/Netflix Dataset.csv')
df.head(1)

df.shape

df.describe()

df.info()

df['Category'] = df['Category'].astype('category')
df['Country'] = df['Country'].astype('category')
df['Rating'] = df['Rating'].astype('category')
df['Type'] = df['Type'].astype('category')
df['Release_Date'] = pd.to_datetime(df['Release_Date'], errors='coerce')

df.info()

df.isna().sum()

df.duplicated().sum()

df.drop_duplicates(inplace=True)

df['Director'] = df['Director'].fillna('Unknown')

df['Cast'] = df['Cast'].fillna('Unknown Cast')

df['Country'] = df['Country'].cat.add_categories(['Unknown']).fillna('Unknown')

median_date = df['Release_Date'].median()
df['Release_Date'] = df['Release_Date'].fillna(median_date)

df['Rating'] = df['Rating'].cat.add_categories(['Unknown Rating']).fillna('Unknown Rating')

df.isna().sum()

df = df.applymap(lambda x: x.strip() if isinstance(x, str) else x)

df[['Duration_Int', 'Duration_Unit']] = df['Duration'].str.extract(r'(\d+)\s*(\w+)')
df['Duration_Int'] = pd.to_numeric(df['Duration_Int'], errors='coerce')

df['Release_Date'] = pd.to_datetime(df['Release_Date'], errors='coerce')
df['Year'] = df['Release_Date'].dt.year

# Q.1) For 'House of Cards', what is the Show Id and Who is the Director of this show ?
house_of_cards = df[df['Title'] == 'House of Cards']
house_of_cards[['Show_Id','Title', 'Director']]

# Q.2) In which year the highest number of the TV Shows & Movies were released ? Show with Bar Graph.
new_show = df['Year']
new_show.value_counts().head()

sns.countplot(data=df, x='Year', hue='Year')
plt.show()

# Q.3) How many Movies & TV Shows are in the dataset ? Show with Bar Graph.
df['Category'].value_counts()

sns.countplot(data=df, x='Category',hue='Category')
plt.show()

# Q. 4) Show all the Movies that were released in year 2000.
df[(df['Category'] == 'Movie') & (df['Year']==2000)]

# Q. 5) Show only the Titles of all TV Shows that were released in India only.
new_title = df[(df['Category']=='TV Show') & (df['Country']== 'India')]
new_title['Title']

# Q. 6) Show Top 10 Directors, who gave the highest number of TV Shows & Movies to Netflix ?
top_director = df['Director'].value_counts().head(10)
sns.barplot(x=top_director.values, y=top_director.index)
plt.xlabel('Numbers of shows and movies')
plt.ylabel('Director')
plt.title('Top 10 Directors on Netflix')
plt.show()

df.head(1)

# Q. 7) Show all the Records, where "Category is Movie and Type is Comedies" or "Country is United Kingdom".

only_uk = df[
    ((df['Category'] == 'Movie') & (df['Type'] == 'Comedies') & (df['Country'] == 'United Kingdom'))]
only_uk = df[df['Country'] == 'United Kingdom']
only_uk.head(2)

# Q. 8) In how many movies/shows, Tom Cruise was cast ?
tom_cruise = df[df['Cast'].str.contains('Tom Cruise', na=False)]
len(tom_cruise)

# Q. 9) What are the different Ratings defined by Netflix ?
sorted(df['Rating'].dropna().unique())

#  Q. 9.1) How many Movies got the 'TV-14' rating, in Canada ?
rating=df[(df['Category']=='Movies') & (df['Rating']=='TV-14') & (df['Country']=='Canada')]
len(rating)

# Q. 9.2) How many TV Shows got the 'R' rating, after year 2018 ?
year = df[(df['Category']=='TV Shows') & (df['Rating']=='R') &
          (df['Year']>2018)]
len(year)

df.head(2)

# Q.10) What is the maximum duration of a Movie/Show on Netflix ?
df['Duration_Int'].max()

# Q.11) Which individual country has the Highest No. of TV Shows ?
tv_shows = df[df['Category']=='TV Show']
top_country = tv_shows['Country'].value_counts().idxmax()
tv_shows['Country'].value_counts().max()

# Q. 12) How can we sort the dataset by Year ?
df.sort_values(by='Year', ascending=True)

df.head(2)

